# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Test
        run: |
          npm ci
          npm run test
      # Runs a set of commands using the runners shell
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@1
        with:
          node_version: '10.x'
      - name: Setup .npmrc
        run: |
          echo _auth=${NPM_PUBLISH_KEY} >> .npmrc
          echo email=${NPM_EMAIL} >> .npmrc
          echo always-auth=true >> .npmrc
          npm ci
          npm run build
          npm version --no-git-tag-version $(npm view <yourProject>@latest version)
          npm version --no-git-tag-version prerelease
          npm publish
