# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.4

      # Runs a single command using the runners shell
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14.x'
      - name: Test
        run: |
          npm ci
          npm run test
      # Runs a set of commands using the runners shell
  publish:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node_version: '14.x'
      - id: install 
          run: npm ci
      - id: build
          run: npm run build
      - id: setup-npmrc
          run: |
            echo _auth=${secrets.NPM_PUBLISH_KEY} >> .npmrc
            echo email=${secrets.NPM_EMAIL} >> .npmrc
            echo always-auth=true >> .npmrc
          
      - id: publish
        uses: JS-DevTools/npm-publish@v1
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
